AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  niwanowa_rssfeed

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Runtime: python3.11

Resources:

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors: "'*'"
      DefinitionBody:
        'Fn::Transform':
          Name: AWS::Include
          Parameters:
            Location: "./niwanowa_rssfeed_api/swagger.yaml"
  
  S3File:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub niwanowa-rssfeed-${AWS::AccountId}-${AWS::StackName}

  GetRSSFeedFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: niwanowa_rssfeed_functions/get/
      Handler: get.lambda_handler
      Events:
        GetRSSFeed:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /
            Method: get

  PostRSSFeedFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: niwanowa_rssfeed_functions/post/
      Handler: post.lambda_handler
      Events:
        PostRSSFeed:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /
            Method: post

  DeleteRSSFeedFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: niwanowa_rssfeed_functions/delete/
      Handler: delete.lambda_handler
      Events:
        DeleteRSSFeed:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{id}
            Method: delete

  PutRSSFeedFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: niwanowa_rssfeed_functions/put/
      Handler: put.lambda_handler
      Events:
        PutRSSFeed:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{id}
            Method: put

  ResetRSSFeedFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: niwanowa_rssfeed_functions/reset/
      Handler: reset.lambda_handler
      Events:
        ResetRSSFeed:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /reset
            Method: get

Outputs:
  ApiGateway:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/"